---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configure-stackrox-integration
  namespace: {{ index .Values "stackrox-chart" "stackrox" "namespace" | quote }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configure-stackrox-integration-local
  namespace: {{ index .Values "stackrox-chart" "stackrox" "namespace" | quote }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "platform.stackrox.io"
    resources:
      - "securedclusters"
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configure-stackrox-integration-local
  namespace: {{ index .Values "stackrox-chart" "stackrox" "namespace" | quote }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configure-stackrox-integration-local
subjects:
  - kind: ServiceAccount
    name: configure-stackrox-integration
    namespace: {{ index .Values "stackrox-chart" "stackrox" "namespace" | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configure-stackrox-integration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - "serviceaccounts"
      - "secrets"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configure-stackrox-integration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configure-stackrox-integration
subjects:
  - kind: ServiceAccount
    name: configure-stackrox-integration
    namespace: {{ index .Values "stackrox-chart" "stackrox" "namespace" | quote }}
