---
apiVersion: v1
kind: Namespace
metadata:
 name: {{ index .Values "logging" "namespace" | quote }}
 labels:
   openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
 name: openshift-operators-redhat
 labels:
   openshift.io/cluster-monitoring: "true"
