{{- if .Values.docs.devfile }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.docs.devfile.configmap_name }}
  namespace: {{ $.Values.docs.namespace }}
data:
  all.json: {{ $.Values.docs.devfile.custom_path }}
{{- end }}
