{{- if .Values.docs }}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: "{{ .Values.docs.name }}"
  namespace: "{{ .Values.docs.namespace }}"
  labels:
    app: "{{ .Values.docs.name }}"
spec:
  replicas: 1
  selector:
    app: "{{ .Values.docs.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.docs.name }}"
    spec:
      containers:
      - image: "{{ .Values.docs.image }}"
        imagePullPolicy: Always
        name: "{{ .Values.docs.name }}"
        ports:
        - name: http 
          containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: "/dev/termination-log"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
{{- end }}
